apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      volumes:
      - name: data-store
        persistentVolumeClaim:
          claimName: jaeger
      - name: configmap-volume
        configMap:
          name: jaeger
          defaultMode: 0777 ## but still write-protected :-(
      containers:
        - name: jaeger
          imagePullPolicy: Always
          livenessProbe:
           httpGet:
             path: /
             port: 16686
             scheme: HTTP
           initialDelaySeconds: 19
           periodSeconds: 30
           failureThreshold: 6
           successThreshold: 1
           timeoutSeconds: 5
          readinessProbe:
           httpGet:
             path: /
             port: 16686
             scheme: HTTP
           initialDelaySeconds: 19
           periodSeconds: 32
           failureThreshold: 11
           successThreshold: 1
           timeoutSeconds: 5
          image: jaegertracing/all-in-one:latest
          ports:
          - name: frontend
            containerPort: 16686
            protocol: TCP          
          - name: tcpjaegerthrift
            containerPort: 14268
            protocol: TCP
          - name: tcpmodelproto
            containerPort: 14250
            protocol: TCP
          command: ["/bin/sh","-c"]
          args:
            - >
              /go/bin/all-in-one-linux
              --log-level=debug
#              while true; do echo ready_to_login; sleep 59;done
          volumeMounts:
          - name: configmap-volume
            mountPath: /config
          resources:
            limits:
              cpu: "300m"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "200Mi"