resources:
  - deployment.yaml
  - hpa.yaml  
  - service.yaml
  - route_http.yaml
  - pvc.yaml
crds:
  - ./crds/openshift-route.json
configMapGenerator:
- name: jaeger
  files:
    - its_a_file.txt=config/its_a_file.txt
commonLabels:
  owner: thetom42
  component: jaeger
  nickname: jaeger
commonAnnotations:
  email: "thetom42@gmail.com"
generatorOptions:
  labels:
    app: jaeger
