apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-carmen-jaeger
  labels:
    app: carmen-jaeger
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
