apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 25500ms
  labels:
    app: carmen-jaeger
  name: route-carmen-jaeger
spec:
  host: repaced-real-name
  port:
    targetPort: frontend
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: service-carmen-jaeger
    weight: 100

