version: '3.0'
services:
  krakend:
    #container_name: krakend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/thetom42/repos/thetom42/krakend-debug:/krakend
    #THESE 4 LINES are IMPORTANT FOR DEBUGGING
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    ports:
      - 8080:8080
      - 8090:8090 
      - 40000:40000   ## THIS PORT IS THE DEBUGGER PORT THAT NEED TO BE EXPOSED.
    #THIS IS THE SAME AS THE ENTRYPOINT notice the --  --config for passing parameters
    command: /go/bin/dlv --headless --listen=:40000 --api-version=2 exec /debug/krakend -- run -ddd -c /debug/krakend.json  
