apiVersion: v1
kind: Service
metadata:
  name: krakend-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: krakend-service
