apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
crds:
  - ./crds/openshift-route.json
vars:
- name: CI_COMMIT_SHA
  objref:
    kind: ConfigMap
    name: influx-krakend-setup
    apiVersion: v1
  fieldref:
    fieldpath: data.CI_COMMIT_SHA
- name: CONTAINER_NAME
  objref:
    kind: ConfigMap
    name: influx-krakend-setup
    apiVersion: v1
  fieldref:
    fieldpath: data.CONTAINER_NAME
- name: IMAGE_NAME
  objref:
    kind: ConfigMap
    name: influx-krakend-setup
    apiVersion: v1
  fieldref:
    fieldpath: data.IMAGE_NAME
- name: INGRESS_HOSTNAME
  objref:
    kind: ConfigMap
    name: influx-krakend-setup
    apiVersion: v1
  fieldref:
    fieldpath: data.INGRESS_HOSTNAME
configMapGenerator:
# environment variables from runner
# static environment variables
  - name: influx-krakend-setup
    envs: [predefined.env,environment-properties.env]
    behavior: create
    files:
    - config/all_dashboards.yml
    - influx_krakend_setup.sh
secretGenerator:
  - name: sst-influx-cert
    type: kubernetes.io/tls
    files:
    - tls.crt
    - tls.key
configurations:
  - configurations.yaml

commonAnnotations:
  email: "DL-VLCarmenCCSystemTeam@dli.telekom.com"

#
# patch below for a unique deploy
#

# avoid name clash on all kubernetes objects
nameSuffix: -uniq

# find all kubernetes objects through unique label
commonLabels:
  dist: 9474d3a0-c498-11ec-9d64-0242ac120002

# label config maps and secrets in addition to commonLabels with labels below
generatorOptions:
  disableNameSuffixHash: false
  labels:
    distm: uniq
