version: "3"
services:
#  grafana:
#    build:
#      dockerfile: Dockerfile
#      context: ./grafana
#    ports:
#      - "3003:3000"
  influxdb:
    image: influxdb:1.8
    environment:
      - "INFLUXDB_DB=krakend"
      - "INFLUXDB_USER=krakend"
      - "INFLUXDB_USER_PASSWORD=krakend"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=supersecretpassword"
    ports:
      - "8086:8086"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - "15672:15672"
#  fake_api:
#    image: jaxgeller/lwan
#    volumes:
#      - ./data:/lwan/wwwroot
#    ports:
#      - "8000:8080"
#  web:
#    build:
#      context: ./web
#    ports:
#      - "3000:3000"
#  kraken_designer:
#    image: devopsfaith/krakendesigner:v2.0
#    ports:
#      - 8787:80
  krakend_ce:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    # Overrides default command so things don't shut down after the process ends.
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
#  jwt_revoke:
#    build:
#      context: ./jwt-revoker
#    ports:
#      - "9000:8080"
#    depends_on:
#      - krakend_ce
